apiVersion: v1
kind: Service
metadata:
  name: router
  namespace: fission
  labels:
    svc: router
spec:
  ports:
  - name: 8888-tcp
    port: 80
    targetPort: 8888
  selector:
    svc: router

---
apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: fission
  labels:
    svc: controller
spec:
  ports:
  - name: 8888-tcp
    port: 80
    targetPort: 8888
  selector:
    svc: controller

---
apiVersion: v1
kind: Route
metadata:
  labels:
  context: fission-router
  name: fission-router
  namespace: fission
spec:
  host: fission-router.cloudapps.cloud-cafe.in
  port:
    targetPort: 8888-tcp
  to:
    kind: Service
    name: router

---
apiVersion: v1
kind: Route
metadata:
  labels:
  context: fission-controller
  name: fission-controller
  namespace: fission
spec:
  host: fission-controller.cloudapps.cloud-cafe.in
  port:
    targetPort: 8888-tcp
  to:
    kind: Service
    name: controller
